import smtplib
from email.mime.text import MIMEText
import os


def send_email(jobs):
    # Get email configuration from environment variables
    email_from = os.environ.get("EMAIL_FROM")
    email_to = os.environ.get("EMAIL_TO")
    email_user = os.environ.get("EMAIL_USER")
    email_app_password = os.environ.get("EMAIL_APP_PASSWORD")
    
    if not all([email_from, email_to, email_user, email_app_password]):
        raise ValueError("Missing email configuration. Please set EMAIL_FROM, EMAIL_TO, EMAIL_USER, and EMAIL_APP_PASSWORD environment variables.")
    
    html = """
    <html>
    <body style="font-family: Arial; background:#f4f6f8; padding:20px;">
        <h2 style="color:#2b6cb0;">🚀 Your Curated Product Job Matches</h2>
        <p>Here are your top relevant roles:</p>
    """

    for job in jobs:
        html += f"""
        <div style="margin-bottom:20px; padding:15px; border:1px solid #ddd; border-radius:10px; background:white;">
            <h3>{job['title']}</h3>
            <p><b>Company:</b> {job.get('company', 'N/A')}</p>
            <p><b>Match Score:</b> {job.get('score', 'N/A')}</p>
            <a href="{job['url']}" style="color:#2b6cb0;">Apply Now</a>
        </div>
        """

    html += """
        <p style="margin-top:20px; font-size:12px; color:gray;">
        Generated by your Personal Job Agent 🤖
        </p>
    </body>
    </html>
    """

    msg = MIMEText(html, "html")
    msg["Subject"] = "🚀 Your Product Job Matches"
    msg["From"] = email_from
    msg["To"] = email_to

    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(email_user, email_app_password)

    print("📤 Sending email...")
    server.send_message(msg)
    server.quit()

    print("✅ Email sent successfully!")